# Generated by Django 5.1.1 on 2024-09-25 17:44

from django.db import migrations

from pgvector.django import VectorExtension

class Migration(migrations.Migration):
    operations = [
        VectorExtension()
    ]
