# Generated by Django 5.1.1 on 2024-09-26 10:26

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('code', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='products/')),
                ('title_embedding', pgvector.django.vector.VectorField(dimensions=300, null=True)),
                ('image_embedding', pgvector.django.vector.VectorField(dimensions=300, null=True)),
            ],
        ),
    ]
