# Generated by Django 5.1.1 on 2024-09-26 11:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1000, null=True),
        ),
    ]
