# Generated by Django 5.1.1 on 2024-09-27 09:15

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vectors', '0004_alter_product_image_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_embedding',
            field=pgvector.django.vector.VectorField(dimensions=512, null=True),
        ),
    ]
